### ISSUE TITLE
More visual content

### ISSUE THREAD

**Issue by ron-popov** [Professor-L/cube-timer#1]
It would be nice if you could see a preview of the scramble and a graph of your solves over time.

**Comment by professor-l** [comment]
The preview isn’t doable, sadly.  The scramble library I’m using is outdated and the scramble preview SVG drawing doesn’t work at all.  I may write my own scramble library, but for now that feature has to be one for the future.

- Elle

**Comment by ron-popov** [comment]
What about time graphs ?

**Comment by professor-l** [comment]
That I can probably muster up with a js library.  It’s been added to the feature list - thanks for the email!

- Elle
