### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by haylinmoore** [Professor-L/cube-timer#2]
I want to use this in a project, what license is this code made public under?

**Comment by professor-l** [comment]
@herohamp - I wrote all the code, but there's no copyright and thus no license.  I'm 18, I don't have time for that crap.  Do with it what you choose.  I'd prefer to be given credit, but it's not technically required :).

Good luck with your project!

**Comment by haylinmoore** [comment]
Ok thank you :) I will make sure to give you credit. By the way adding a license is super simple https://stackoverflow.com/questions/31639059/how-to-add-license-to-an-existing-github-project shows you how with https://choosealicense.com/ explaining each
